name: "favicon-marquee-e2e"
services:
    browser:
        image: selenium/standalone-chrome:132.0
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4444"]
            interval: 3s
        volumes:
            - ../../examples:/files/examples
            - ../../lib:/files/lib
        environment:
            - SE_SCREEN_WIDTH=1920
            - SE_SCREEN_HEIGHT=150
        ports:
            - "4444:4444"

    browser_recording:
        image: selenium/video:ffmpeg-7.1-20250202
        user: root
        volumes:
            - ../../:/videos
        depends_on:
            node:
                condition: service_healthy
        environment:
            - SE_SCREEN_WIDTH=306
            - SE_SCREEN_HEIGHT=46
            - FRAME_RATE=60
            - DISPLAY_CONTAINER_NAME=browser
            - FILE_NAME=favicon_marquee_demo.mp4

    node:
        image: node:18
        depends_on:
            browser:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "test", "-f", "/tmp/favicon-marquee-node-container-ready"]
            interval: 3s
            retries: 5
        volumes:
            - ../../node_modules:/files/node_modules
            - ../../package.json:/files/package.json
            - ../../lib/__tests__/e2e.js:/files/__tests__/e2e.js
        environment:
            - SELENIUM_REMOTE_URL=http://browser:4444
        command:
            - /files/__tests__/e2e.js
