name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repository
        uses: actions/checkout@v4

      - name: set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: npm install
        run: npm ci

      - name: check formatting (Prettier)
        run: npm run format

      - name: compile TypeScript
        run: npm run compile

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repository
        uses: actions/checkout@v4

      - name: set up ffmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: npm install
        run: npm ci

      - name: generate recording mp4
        run: npm run test

      - name: create recording gif
        run: ./generate-gif.sh

      - name: create recording artifact
        # TODO comment link of artifact on PRs, can use https://github.com/unsplash/comment-on-pr, blocked on https://github.com/actions/upload-artifact/issues/406
        uses: actions/upload-artifact@v4
        with:
          path: scrolling-favicon.gif
