name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repository
        uses: actions/checkout@v3

      - name: set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: npm install
        run: npm ci

      - name: check formatting (Prettier)
        run: npm run format

      - name: compile TypeScript
        run: npm run compile
