name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repository
        uses: actions/checkout@v4

      - name: set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: npm install
        run: npm ci

      - name: check formatting (Prettier)
        run: npm run format

      - name: compile TypeScript
        run: npm run compile

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repository
        uses: actions/checkout@v4

      - name: set up ffmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: npm install
        run: npm ci

      - name: generate recording mp4
        run: npm run test

      - name: create recording gif
        run: ./generate-gif.sh

      - name: create recording artifact
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          path: scrolling-favicon.gif

      - name: PR Comment
        if: github.event_name == 'pull_request'
        shell: bash {0} # bypass GH Actions setting "-e" by default https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#custom-shell
        run: |
          export RETENTION_DATE=$(date -d "+90 days" +"%e %b %Y")
          export ARTIFACT_URL=${{ steps.artifact-upload.outputs.artifact-url }}
          cat .github/workflows/pr-comment.md | envsubst > /tmp/comment.md
          
          gh pr comment $PRNUM --edit-last --body-file /tmp/comment.md
          if [ $? != 0 ]; then
            gh pr comment $PRNUM --body-file /tmp/comment.md
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}
          ARTIFACT_URL: ${{ steps.artifact-upload.outputs.artifact-url }}
